# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 07:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.HelpMethods.helpers
import utils.validate_files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoriosVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesorio', models.CharField(max_length=255)),
                ('existe', models.BooleanField(default=True)),
                ('comentario', models.TextField(blank=True)),
                ('codigo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionesGeneralesVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte', models.CharField(max_length=255)),
                ('comentario', models.TextField(blank=True)),
                ('codigo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetallesDatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieza', models.CharField(max_length=255)),
                ('tipo_dano', models.BooleanField(default=True)),
                ('costo_aproximado', models.DecimalField(decimal_places=2, max_digits=21)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosPresentados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('recibido', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MecanicaVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte', models.CharField(max_length=255)),
                ('comentario', models.TextField(blank=True)),
                ('codigo', models.CharField(max_length=255, unique=True)),
                ('fk_estado_vehiculo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rcs.EstadoVehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudInspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siendo_verificada', models.IntegerField()),
                ('editable', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now=True, null=True, verbose_name=[b'%d/%m/%Y'])),
                ('ruta', utils.validate_files.ContentTypeRestrictedFileField(blank=True, max_length=500, null=True, upload_to=utils.HelpMethods.helpers.get_file_path_solicitud)),
                ('fk_estado_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcs.EstadoSolicitud')),
                ('fk_inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitularVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=255, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrajoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=255, unique=True)),
                ('parentesco', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=255, unique=True)),
                ('cap_puestos', models.IntegerField()),
                ('cilindros', models.CharField(max_length=255)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=21)),
                ('color', models.CharField(max_length=255)),
                ('kilometraje', models.CharField(max_length=255)),
                ('serial_carroceria', models.CharField(max_length=255)),
                ('serial_motor', models.CharField(max_length=255)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=21)),
                ('modelo', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('anho', models.IntegerField()),
                ('accesorios_vehiculo', models.ManyToManyField(to='rcs.AccesoriosVehiculo')),
                ('condiciones_generales_vehiculo', models.ManyToManyField(to='rcs.CondicionesGeneralesVehiculo')),
                ('detalles_datos', models.ManyToManyField(to='rcs.DetallesDatos')),
                ('documentos_presentados', models.ManyToManyField(to='rcs.DocumentosPresentados')),
                ('fk_inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fk_tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcs.TipoVehiculo')),
                ('fk_titular_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcs.TitularVehiculo')),
                ('fk_trajo_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcs.TrajoVehiculo')),
                ('mecanica_vehiculo', models.ManyToManyField(to='rcs.MecanicaVehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='fk_titular_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcs.TitularVehiculo'),
        ),
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='fk_vehiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rcs.Vehiculo'),
        ),
        migrations.AddField(
            model_name='condicionesgeneralesvehiculo',
            name='fk_estado_vehiculo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rcs.EstadoVehiculo'),
        ),
    ]
