# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trajovehiculo',
            old_name='parentesco',
            new_name='fk_parentesco',
        ),
    ]
