# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
