# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesoriosvehiculo',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesvehiculo',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mecanicavehiculo',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
