# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcs', '0002_solicitudinspeccion_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='fk_estado_solicitud',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rcs.EstadoSolicitud'),
        ),
    ]
