# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcs', '0002_remove_solicitudinspeccion_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='fk_trajo_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcs.TrajoVehiculo'),
        ),
    ]
