# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcs', '0002_auto_20170422_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionesgeneralesvehiculo',
            name='fk_estado_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcs.EstadoVehiculo'),
        ),
        migrations.AlterField(
            model_name='mecanicavehiculo',
            name='fk_estado_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcs.EstadoVehiculo'),
        ),
    ]
