# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcs', '0003_auto_20170423_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadovehiculo',
            name='clase',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
