# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcs', '0004_auto_20170423_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='accesorios_vehiculo',
            field=models.ManyToManyField(to='rcs.AccesoriosVehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='condiciones_generales_vehiculo',
            field=models.ManyToManyField(to='rcs.CondicionesGeneralesVehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='detalles_datos',
            field=models.ManyToManyField(to='rcs.DetallesDatos'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='documentos_presentados',
            field=models.ManyToManyField(to='rcs.DocumentosPresentados'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='mecanica_vehiculo',
            field=models.ManyToManyField(to='rcs.MecanicaVehiculo'),
        ),
    ]
