# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcs', '0004_remove_vehiculo_fk_trajo_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='fk_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcs.Vehiculo'),
        ),
    ]
