# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcs', '0005_auto_20170516_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='peso',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
