# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-11 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcs', '0006_auto_20170516_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='numero_ticket',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
