# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcs', '0006_auto_20170425_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoManejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fk_tipo_manejo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcs.TipoManejo'),
        ),
    ]
