# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-11 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcs', '0008_auto_20170711_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinspeccion',
            name='codigo',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudinspeccion',
            name='numero_ticket',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
