# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcs', '0010_marcavehiculo_modelovehiculo_parentesco'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelovehiculo',
            name='fk_marca_vehiculo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rcs.MarcaVehiculo'),
            preserve_default=False,
        ),
    ]
