# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20170314_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
