# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_usuario_cedula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_usuario',
            new_name='username',
        ),
    ]
